<div class="container">
    <div class="card">
        <div class="card-body">
            <h5>Hello,</h5>
            <p>This is a microframework Productive, for yours little and quickly projects.</p>
            <p>Enjoy as much as you can.</p>
            <p>Good work.</p>
            <a href="https://github.com/calixto/productive/wiki" target="__BLANK" class="btn btn-primary">See a documentation</a>
        </div>
    </div>
</div>