<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <link href="<?php echo $this->url('node_modules/@fortawesome/fontawesome-free/css/all.min.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->url('node_modules/bootstrap/dist/css/bootstrap.css'); ?>" rel="stylesheet" type="text/css"/>
        <!--<link href="<?php echo $this->url('node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css'); ?>" rel="stylesheet" type="text/css"/>-->
        <link href="<?php echo $this->url('node_modules/noty/lib/noty.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->url('css/main.css'); ?>" rel="stylesheet" type="text/css"/>
        <?php foreach ($this->__css as $__css) : ?>
            <?php if ($__css): ?>
                <link rel="stylesheet" type="text/css" href="<?php echo $this->url($__css); ?>">
            <?php endif; ?>
        <?php endforeach; ?>
        <link rel="shortcut icon" href="<?php echo Productive\Http\Url::root(); ?>../assets/img/favicon.png"/>
        <title>My Productive Project</title>
    </head>

    <body class="d-flex flex-column h-100">
        <div id="overlay">
            <a href="javascript:void(0);" ></a>
        </div>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">

                    </a>
                    <div class="collapse navbar-collapse" id="navbarText">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="#">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Features</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Pricing</a>
                            </li>
                        </ul>
                    </div>
                    <button class="btn btn-default js-main-menu">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
            </nav>
        </header>
        <menu style="padding-top: 70px; display:none;">
            <?php $this->addTemplate('public/menu.phtml'); ?>
        </menu>
        <main style="padding-top: 70px;">
            <?php echo $contentPage ?>
        </main>
        <footer class="footer mt-auto py-3 bg-light fixed-bottom">
            <div class="container-fluid">
                <span class="text-muted">Place sticky footer content here.</span>
                <span class="text-muted float-end">V 1.0</span>
            </div>
        </footer>        
        <script type="text/javascript" src="<?php echo $this->url('node_modules/@fortawesome/fontawesome-free/js/all.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->url('node_modules/jquery/dist/jquery.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->url('node_modules/bootstrap/dist/js/bootstrap.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->url('node_modules/jquery-mask-plugin/dist/jquery.mask.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->url('node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->url('node_modules/noty/lib/noty.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->url('node_modules/mo-js/build/mo.js'); ?>"></script>
        <script type="text/javascript">var _JS = <?php echo ${' JS'} ?></script>
        <script type="text/javascript" src="<?php echo $this->url('js/main.js'); ?>"></script>
        <?php foreach ($this->__scripts as $__script) : ?>
            <?php if ($__script): ?>
                <script type="text/javascript" src="<?php echo $this->url($__script); ?>"></script>
            <?php endif; ?>
        <?php endforeach; ?>
    </body>
</html>