            <div class="row">
                <h3>Main Menu</h3>
                <div class="col-sm-2">
                    <h5>Bookmarks</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Much longer nav link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Much longer nav link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-8">
                    <div class="row">
                        <div class="col-sm-7"></div>
                        <div class="col-sm-4">
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
                                <span class="input-group-text" >@</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <h5>Block 1</h5>
                        <ul class="nav nav-pills nav-fill">
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Much longer nav link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Much longer nav link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                            </li>
                        </ul>
                    </div>
                    <div class="row">
                        <h5>Block 2</h5>
                        <ul class="nav nav-pills nav-fill">
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Much longer nav link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">New Link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Much longer nav link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">New Link</a>
                            </li>
                        </ul>
                        <h5>Block 3</h5>
                        <ul class="nav nav-pills nav-fill">
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Much longer nav link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Much longer nav link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">New Link</a>
                            </li>
                            <li class="nav-item col-sm-4">
                                <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Other Link</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <h5>User Configs</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item col-sm-4">
                            <a class="nav-link" href="#">User Info</a>
                        </li>
                        <li class="nav-item col-sm-4">
                            <a class="nav-link" href="#">Personalization</a>
                        </li>
                        <li class="nav-item col-sm-4">
                            <a class="nav-link" href="#">Security</a>
                        </li>
                    </ul>
                </div>
            </div>
